### ISSUE TITLE
Implement booking functionality with real-time updates.

### ISSUE THREAD

**Issue by lindawendel** [lindawendel/TeamBeerly#7]
- [ ] Click-and-book
- [ ] Instant response: "Booked"
- [ ] update view by interval maybe? each 10 seconds or something?
- [ ] Create logic for a booking slot to be "taken" when opened by Patient/Caregiver even tho it's not fully sent? Possible solutions might contain SignalR or any other WebSocket service?

**Comment by fredrikgreco** [comment]
will not use signalR or websocket service, will use easier and faster version

**Comment by fredrikgreco** [comment]
this branch is bad and will be replaced now
